[package]
name = "fastflow_ui_macos"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "fastflow-app"
path = "src/main.rs"

[dependencies]
fibre.workspace = true
chrono.workspace = true
fastflow_capture.workspace = true
fastflow_core.workspace = true
fastflow_daemon.workspace = true
fastflow_render.workspace = true
global-hotkey.workspace = true
fastflow_desktop.workspace = true
objc2.workspace = true
objc2-app-kit.workspace = true
objc2-av-foundation.workspace = true
objc2-av-kit.workspace = true
objc2-core-media.workspace = true
objc2-foundation.workspace = true
objc2-user-notifications.workspace = true
png.workspace = true
block2.workspace = true
serde.workspace = true
serde_json.workspace = true
toml.workspace = true
tray-icon.workspace = true
winit.workspace = true
